config/routes.rb
Glash::Application.routes.draw do
  comfy_route :cms_admin, :path => '/cmsadmin'

  scope controller: :pages do
    get 'greetings' => :greetings, as: :greetings
    get 'goodbye' => :goodbye, as: :goodbye
  end
   
  ActiveAdmin.routes(self)

  root to: "pages#default"
  
  devise_for :users, :controllers => {:registrations => "registrations"}

  resources :users do
    member do
      get :avatar
      get :load_avatar
    end

    resources :contacts
  end

  resources :ideas do
    member {post :vote, as: :vote}
    member {post :moderate, as: :moderate}

    resources :submit, controller: 'submit'
    resources :assets, except: :destroy
    resources :comments, only: [:create]
  end
  
  resources :assets, only: :destroy
  resources :comments, only: [:index, :destroy] do
    member { post :moderate, as: :moderate}
  end

  comfy_route :cms, :path => '/', :sitemap => false

  

end

app/views/shared/_about.haml
.logo_footer= link_to image_tag('logo-footer.png', alt: "Glash!"), root_path
%h1.zagfooter
  Это сайт об идеях и изобретениях, которые мы делаем реальностью. Присылайте нам свои идеи, комментируйте идеи других и зарабатывайте с нами!

-if signed_in?
  =render "shared/contact_user"
-else
  =render "shared/subscribe_news"

=render "shared/social_footer"
.clearfix

app/views/shared/_contact_user.html.haml
.contact-detail
  %ul.contact
    %li
      %p
        %i.icon.icon-envelope
        %strong Email:
        %a{href: "mailto:support@glash.ru"} support@glash.ru
    -#
      %li
        %p
          %i.icon.icon-map-marker
          %strong Информация
      %li
        %p
          %i.icon.icon-phone
          %strong Телефон
          (123) 456-7890

app/views/shared/_container.html.haml
.container
  .row.hite
    - if check_help_pages
      = render :partial => "pages/help_pages"
    
    -else
      .col-md-12
        = render :partial => "shared/notice_alert"
        = yield

app/views/shared/_copyright.html.haml
.footer-copyright
  .container
    .row
      .col-md-6
        %p Glash! © 2014
      .col-md-6
        %ul.social-icons
          %li
            %a{href: "https://vk.com/public80408399", rel: "tooltip", target: "_blank", title: "VKontakte"}
              %i.icon.icon-vk
          %li
            %a{href: "https://twitter.com/glash_ru", rel: "tooltip", target: "_blank", title: "Twitter"}
              %i.icon.icon-twitter
          %li
            %a{href: "https://www.facebook.com/pages/Glash/1539619519617370", rel: "tooltip", target: "_blank", title: "Facebook"}
              %i.icon.icon-facebook

app/views/shared/_footer.html.haml
%footer#footer
  .container
    .row
      .col-md-3
        =render "shared/about"

      .col-md-3
        =render "shared/newest_ideas"

      .col-md-3
        =render "shared/texts"

      .col-md-3
        =render "shared/most_active"

  =render "shared/copyright"
  

app/views/shared/_header.html.haml
-# Ivan
%header
  .container
    %h1.logo 
      =link_to root_path do
        %img{alt: "Glash", "data-small-height" => "44", src: image_path('logo.png') }
    .navbar-collapse.nav-main-collapse.collapse
      #headerSearch.search
        %a#headerSearchOpen{href: root_path}
          %i.icon.icon-search
        .search-input
          %form#headerSearchForm{action: "", method: "get"}
            .input-group
              %input#q.form-control.search{name: "q", placeholder: "Поиск...", type: "text"}/
              %span.input-group-btn
                %button.btn.btn-primary{type: "button"}
                  %i.icon.icon-search
      %nav.nav-main.mega-menu
        %ul#mainMenu.nav.nav-pills.nav-main
          -#
            %li.dropdown.active
            %a.dropdown-toggle{href: root_path}
              Главная
              %i.icon.icon-caret-down
            %ul.dropdown-menu
              %li
                %a{href: root_path} Первый
              %li
                %a{href: root_path} Первый
              %li
                %a{href: root_path} Первый
              %li
                %a{href: root_path} Первый
          -#      
            - if current_page?(ideas_path)
              - css_class_ideas = 'active'
            -else 
              - css_class_ideas = ''

            #{controller.controller_name.to_s}.#{controller.action_name.to_s}" == "pages.index"
            - css_class_ideas = current_page('ideas', 'index')

          - css_class_ideas = controller.controller_name.to_s == "ideas" ? 'active' : ''
          %li{:class => css_class_ideas}
            %a{href: ideas_path}
              Идеи
          -#%li
            %a{href: root_path}
              Проекты
          -#%li.dropdown
            %a.dropdown-toggle{href: root_path}
              Конкурсы
              %i.icon.icon-caret-down
            %ul.dropdown-menu
              %li
                %a{href: root_path} Первый  
              %li
                %a{href:root_path} Второй
              %li
                %a{href: root_path} Третий
              %li
                %a{href: root_path} Все

          -#
            %li.dropdown
            %a.dropdown-toggle{href: root_path}
              Магазин
              %i.icon.icon-caret-down
            %ul.dropdown-menu
              %li
                %a{href: root_path} Первый
              %li
                %a{href: root_path} Первый
              %li
                %a{href: root_path} Первый
              %li
                %a{href: root_path} Первый
              %li
                %a{href: root_path} Первый
              %li.dropdown-submenu
                %a{href: root_path} Первый
                %ul.dropdown-menu
                  %li
                    %a{href: root_path} Первый
                  %li
                    %a{href: root_path} Первый
                  %li
                    %a{href: root_path} Первый
                  %li
                    %a{href:root_path} Первый
                  %li
                    %a{href: root_path} Первый
                  %li
                    %a{href: root_path} Первый
              %li
                %a{href: root_path} Первый
              %li
                %a{href: root_path} Первый
              %li
                %a{href: root_path} Первый
              %li
                %a{href: root_path} Первый
          - css_class_users = current_page?(users_path) ? 'active' : ''
          %li{:class => css_class_users} 
            %a{href: users_path}
              Сообщество
          -#%li.dropdown
            %a.dropdown-toggle{href: root_path}
              Контакты
              %i.icon.icon-caret-down
            %ul.dropdown-menu
              %li
                %a{href: root_path} Первый
              %li
                %a{href: root_path} Второй

          = render 'shared/menu_item'         
   
    %button.btn.btn-responsive-nav.btn-inverse{"data-target" => ".nav-main-collapse", "data-toggle" => "collapse"}
      %i.icon.icon-bars

app/views/shared/_header_ishodnyi!!!.html.haml
-# Ivan
%header
  .container
    %h1.logo
      /%a{href: home_path}
      =link_to root_path do
        %img{alt: "Glash", "data-small-height" => "44", src: image_path('logo.png') }
    .navbar-collapse.nav-main-collapse.collapse
      #headerSearch.search
        %a#headerSearchOpen{href: root_path}
          %i.icon.icon-search
        .search-input
          %form#headerSearchForm{action: "", method: "get"}
            .input-group
              %input#q.form-control.search{name: "q", placeholder: "Поиск...", type: "text"}/
              %span.input-group-btn
                %button.btn.btn-primary{type: "button"}
                  %i.icon.icon-search
      %nav.nav-main.mega-menu
        %ul#mainMenu.nav.nav-pills.nav-main
          -#
            %li.dropdown.active
            %a.dropdown-toggle{href: root_path}
              Главная
              %i.icon.icon-caret-down
            %ul.dropdown-menu
              %li
                %a{href: root_path} Первый
              %li
                %a{href: root_path} Первый
              %li
                %a{href: root_path} Первый
              %li
                %a{href: root_path} Первый
          %li
            %a{href: root_path}
              Идеи
          %li
            %a{href: root_path}
              Проекты
          %li.dropdown
            %a.dropdown-toggle{href: root_path}
              Конкурсы
              %i.icon.icon-caret-down
            %ul.dropdown-menu
              %li
                %a{href: root_path} Первый  
              %li
                %a{href:root_path} Второй
              %li
                %a{href: root_path} Третий
              %li
                %a{href: root_path} Все

          -#
            %li.dropdown
            %a.dropdown-toggle{href: root_path}
              Магазин
              %i.icon.icon-caret-down
            %ul.dropdown-menu
              %li
                %a{href: root_path} Первый
              %li
                %a{href: root_path} Первый
              %li
                %a{href: root_path} Первый
              %li
                %a{href: root_path} Первый
              %li
                %a{href: root_path} Первый
              %li.dropdown-submenu
                %a{href: root_path} Первый
                %ul.dropdown-menu
                  %li
                    %a{href: root_path} Первый
                  %li
                    %a{href: root_path} Первый
                  %li
                    %a{href: root_path} Первый
                  %li
                    %a{href:root_path} Первый
                  %li
                    %a{href: root_path} Первый
                  %li
                    %a{href: root_path} Первый
              %li
                %a{href: root_path} Первый
              %li
                %a{href: root_path} Первый
              %li
                %a{href: root_path} Первый
              %li
                %a{href: root_path} Первый
          - if current_page?(users_path)
            - css_class_users = 'active'
          -else 
            - css_class_users = ''
          %li{:class => 'dropdown ' + css_class_users}
            %a.dropdown-toggle{href: users_path}
              Сообщество
              %i.icon.icon-caret-down
            %ul.dropdown-menu
              %li
                %a{href: root_path} Первый
              %li
                %a{href: root_path} Первый
              %li
                %a{href: root_path} Первый
              %li
                %a{href: root_path} Первый
          %li.dropdown
            %a.dropdown-toggle{href: root_path}
              Контакты
              %i.icon.icon-caret-down
            %ul.dropdown-menu
              %li
                %a{href: root_path} Первый
              %li
                %a{href: root_path} Второй

          = render 'shared/menu_item'         
   
    %button.btn.btn-responsive-nav.btn-inverse{"data-target" => ".nav-main-collapse", "data-toggle" => "collapse"}
      %i.icon.icon-bars

app/views/shared/_menu_item.html.haml
-if signed_in?
  - css_class = user_css_klass? ? 'active' : ''
    
  %li{:class => 'dropdown ' + css_class}
    -#
      %a.dropdown-toggle{:href=>dashboard_user_path(current_user), 'data-target'=> '#', 'data-toggle' => 'dropdown'}
        =:logged_in.l + ' ' + current_user.login
        %i.icon.icon-caret-down
    %a.dropdown-toggle{href: user_path(current_user)}
      = current_user.fullname

      %i.icon.icon-caret-down
    %ul.dropdown-menu
      -if current_user.is_admin?
        %li= link_to 'Панель администратора', admin_dashboard_path
        %li= link_to 'Панель CMS', '/cmsadmin'
        %li.divider
      -if current_user.is_moderator?
        %li= link_to 'Модерировать комментарии', comments_path
        %li.divider
      
      %li{:class => current_page('users', 'show')}
        = link_to "Мой профиль", user_path(current_user)
      %li{:class => current_page('registrations', 'edit')}
        = link_to "Редактировать профиль", edit_registration_path(current_user)
      %li{:class => current_page('users', 'load_avatar')}
        = link_to "Загрузить аватар", load_avatar_user_path(current_user) unless current_user.avatar_file_name
      %li{:class => current_page('users', 'avatar')}
        = link_to "Редактировать аватар", avatar_user_path(current_user) if current_user.avatar_file_name
      %li{:class => current_page('contacts', 'edit')}
        = link_to "Изменить контакты", edit_user_contact_path(current_user, current_user.contact)
      
      %li.divider
      %li= link_to t(:sign_out), destroy_user_session_path, :method => :delete 

-else
  - if controller_name == 'registrations' && action_name == 'new' 
    - css_class_sign_up = 'active'
  - else 
    - css_class_sign_up = ''
  %li{:class => css_class_sign_up}
    = link_to t(:sign_up), new_registration_path(:user) 

  - if controller_name == 'sessions' && action_name == 'new'
    - css_class_sign_in = 'active'
  - else 
    - css_class_sign_in = ''  
  %li{:class => css_class_sign_in}
    = link_to t(:sign_in), new_user_session_path

    

-#
  %li= link_to "Изменить пароль", edit_password_path(current_user)
  %li= link_to :edit_profile.l, edit_user_path(current_user)
  %li= link_to :edit_account.l, edit_account_user_path(current_user)
  %li= link_to :manage_posts.l, manage_user_posts_path(current_user)
  %li= link_to :inbox.l, user_messages_path(current_user)
  %li.divider
  %li= link_to :my_profile.l, user_path(current_user)
  %li= link_to :my_blog.l, user_posts_path(current_user)
  %li= link_to :photo_manager.l, user_photo_manager_index_path(current_user)
  %li= link_to :my_clippings.l, user_clippings_path(current_user)
  %li= link_to :my_friends.l, accepted_user_friendships_path(current_user)

app/views/shared/_most_active.html.haml
%h4 Самые активные
%ul.list-unstyled.recent-work
  -most_active_users.each do |user|
    %li
      %a.thumb-info{href: users_path(user)}
      =link_to image_tag(user.avatar.url(:thumb), {class: "img.img-responsive", alt: "#{user.fullname}", title: "#{user.fullname}", height: "79",width: "79"}), user
%br/
=link_to users_path, {class: "pull-right most-active-users"} do
  Посмотреть всех
  &nbsp;
  %i.icon.icon-arrow-right

app/views/shared/_new_ideas.html.haml
%h4 Новые Идеи
%ul.list-unstyled.recent-work
  %li
    %a.thumb-info{href: root_path}
      %img.img-responsive{alt: "", height: "78", src: image_path('projects/project-thumb-1.jpg'), width: "78"}/
  %li
    %a.thumb-info{href: root_path}
      %img.img-responsive{alt: "", height: "78", src: image_path('projects/project-thumb-9.jpg'), width: "78"}/
  %li
    %a.thumb-info{href: root_path}
      %img.img-responsive{alt: "", height: "78", src: image_path('projects/project-thumb-3.jpg'), width: "78"}/
  %li
    %a.thumb-info{href: root_path}
      %img.img-responsive{alt: "", height: "78", src: image_path('projects/project-thumb-4.jpg'), width: "78"}/
  %li
    %a.thumb-info{href: root_path}
      %img.img-responsive{alt: "", height: "78", src: image_path('projects/project-thumb-5.jpg'), width: "78"}/
  %li
    %a.thumb-info{href: root_path}
      %img.img-responsive{alt: "", height: "78", src: image_path('projects/project-thumb-11.jpg'), width: "78"}/
  %li
    %a.thumb-info{href: root_path}
      %img.img-responsive{alt: "", height: "78", src: image_path('projects/project-thumb-2.jpg'), width: "78"}/
  %li
    %a.thumb-info{href: root_path}
      %img.img-responsive{alt: "", height: "78", src: image_path('projects/project-thumb-6.jpg'), width: "78"}/
  %li
    %a.thumb-info{href: root_path}
      %img.img-responsive{alt: "", height: "78", src: image_path('projects/project-thumb-7.jpg'), width: "78"}/
%a.btn-flat.pull-right.btn-xs.view-more-recent-work{href: root_path}
  Еще Идеи
  %i.icon.icon-arrow-right

app/views/shared/_notice_alert.html.haml
-if alert
  .alert.alert-danger.alert-dismissible{role: "alert"}
    %button.close{:"data-dismiss" => "alert", type: "button"}
      %span{"aria-hidden" => "true"} &#215;
      %span.sr-only Закрыть
    %p#alert= alert
-if notice
  .alert.alert-success.alert-dismissible{role: "alert"}
    %button.close{:"data-dismiss" => "alert", type: "button"}
      %span{"aria-hidden" => "true"} &#215;
      %span.sr-only Закрыть
    %p#notice= notice
    

app/views/shared/_scripts_and_styles.html.haml
%link{:rel=>"shortcut icon", :href => image_url("favicon.ico")}
%meta{"http-equiv"=>"Content-Type", :content=>"text/html;charset=utf-8"}
= stylesheet_link_tag  "application", media: "all", "data-turbolinks-track" => true

= csrf_meta_tags
%meta{content: "width=device-width, initial-scale=1.0", name: "viewport"}/

%meta{content: "Glash", name: "keywords"}/
%meta{content: "Glash - сайт об идеях и изобретениях, которые мы делаем реальностью. Присылайте нам свои идеи, комментируйте идеи других и зарабатывайте с нами!", name: "description"}/
%meta{content: "glash.ru", name: "author"}/

%title= (yield(:title).empty? ? "Glash - Претвори мечту в реальность!" : yield(:title))
  
-if @meta
  -@meta.each do |key|
    %meta{:name=>key[0], :content=>key[1]}

- if @rss_title && @rss_url
  = auto_discovery_link_tag(:rss, @rss_url, {:title => @rss_title})

/[if IE]
  = stylesheet_link_tag 'ie'
/[if IE 6] 
  = stylesheet_link_tag 'ie6'
/[if IE 7] 
  = stylesheet_link_tag 'ie7'
/[if IE 8] 
  = stylesheet_link_tag 'settings-ie8'

-# if forum_page?
  = stylesheet_link_tag 'forum'
  - unless @feed_icons.blank?
    - @feed_icons.each do |feed|
      = auto_discovery_link_tag :rss, feed[:url], :title => "Subscribe to '#{feed[:title]}'"

= yield :head_css
= javascript_include_tag 'application', "data-turbolinks-track" => true

app/views/shared/_se_analytics.html.haml
-if Rails.env == 'production'

  :javascript
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-54648259-1', 'auto');
    ga('send', 'pageview');


    (function (d, w, c) {
        (w[c] = w[c] || []).push(function() {
            try {
                w.yaCounter26127036 = new Ya.Metrika({id:26127036,
                        clickmap:true,
                        trackLinks:true,
                        accurateTrackBounce:true});
            } catch(e) { }
        });
    
        var n = d.getElementsByTagName("script")[0],
            s = d.createElement("script"),
            f = function () { n.parentNode.insertBefore(s, n); };
        s.type = "text/javascript";
        s.async = true;
        s.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//mc.yandex.ru/metrika/watch.js";
    
        if (w.opera == "[object Opera]") {
            d.addEventListener("DOMContentLoaded", f, false);
        } else { f(); }
    })(document, window, "yandex_metrika_callbacks");

  %img{:alt => "", :src => "//mc.yandex.ru/watch/26127036", :style => "position:absolute; left:-9999px;"}/

app/views/shared/_texts.html.haml
%h4 Информация
%ul.nav.nav-list.primary
  %li
    %a{href: '/help/kak-eto-rabotaet', title: "Помощь"} Помощь
  %li
    %a{href: '/questions-answers', title: "Вопросы и ответы"} Вопросы и ответы
  -#
    %li
      %a{href: root_path, title: "Форум"} Форум
  %li
    %a{href: '/terms', title: "Правила использования"} Правила использования
  %li
    %a{href: '/privacy-policy', title: "Политика конфиденциальности"} Политика конфиденциальности