config/routes.rb
Glash::Application.routes.draw do
  comfy_route :cms_admin, :path => '/cmsadmin'

  scope controller: :pages do
    get 'greetings' => :greetings, as: :greetings
    get 'goodbye' => :goodbye, as: :goodbye
  end
   
  ActiveAdmin.routes(self)

  root to: "pages#default"
  
  devise_for :users, :controllers => {:registrations => "registrations"}

  resources :users do
    member do
      get :avatar
      get :load_avatar
    end

    resources :contacts
  end

  resources :ideas do
    member {post :vote, as: :vote}
    member {post :moderate, as: :moderate}

    resources :submit, controller: 'submit'
    resources :assets, except: :destroy
    resources :comments, only: [:create]
  end
  
  resources :assets, only: :destroy
  resources :comments, only: [:index, :destroy] do
    member { post :moderate, as: :moderate}
  end

  comfy_route :cms, :path => '/', :sitemap => false

  

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  belongs_to :user
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :authenticate_user!
  # before_action :goto_root , only: [:index, :show, :new, :create ]
  # before_action :check_user, only: [:edit, :update, :destroy]
  before_action :check_user, only: [:edit, :update]
  # , only: :update

  filter_resource_access

  # filter_access_to :all, :attribute_check => true
  # filter_resource_access  :attribute_check => true

  def index
  end

  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
    if @contact.update(contact_params)
      redirect_to @user, notice: 'Ваша учётная запись изменена.'
    else
      render :edit
    end
  end

  private

    def check_user
      # unless User.friendly.find(params[:user_id]) == current_user && Contact.find(User.friendly.find(params[:user_id])) == Contact.find(params[:id])
      #   goto_root
      # end
      @user = User.friendly.find(params[:user_id])
      @contact = current_user.contact
    end

    # # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:phone, :phone2, :show_skype, :skype, :show_site, :site,
       :vkontakte, :facebook, :odnoklassniki, :twitter, :linkedin)
    end

    # def goto_root
    #   redirect_to root_path, notice: 'Вы не можете просматривать или редактировать приватные записи других членов сообщества.'
    # end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/edit.html.haml
-title "Редактировать контакты"
%h1
  Редактировать контакты
= semantic_form_for(@contact, url: user_contact_path(@user, @contact), html: { method: :put , :id => 'edit_contact'}) do |f|
  .col-md-3
    = image_tag @user.avatar.url(:thumb), class: "img-thumbnail", width: "192px"
    %br
  .col-md-9
    = f.inputs do
      .col-md-12
      %p
        Телефоны и Skype необходимы для связи только с Вами, они видны только Вам и сотрудникам сайта. 
      %p Вы может сделать видимым для всех логин скайпа и ссылку на gерсональный сайт, отметив соответствующие пункты.
      %p
        Более подробную информацию Вы можете узнать, прочитав наши
      %p  
        #{link_to('Правила защиты информации о пользователях сайта', '/privacy-policy', target: '_blank')}.
      %br/
      .form-group
        .col-md-12                      
          = f.input :phone, as: :phone, :label => t(:phone, scope: "activerecord.attributes.contact"), autofocus: true, :input_html => {:class => "form-control"}, :required => false, placeholder: "+7 (987) 123-4567"
          = f.input :phone2, :label => t(:phone, scope: "activerecord.attributes.contact"), autofocus: true, :input_html => {:class => "form-control"}, :required => false, placeholder: "запасной телефон"
          = f.input :skype, autofocus: true, :input_html => {:class => "form-control"}, :required => false, placeholder: "skype"
          = f.input :show_skype, :as => :boolean, autofocus: true, :required => false
          = f.input :site, autofocus: true, :input_html => {:class => "form-control"}, :required => false, placeholder: "site.ru"
          = f.input :show_site, :as => :boolean, autofocus: true, :required => false
      %hr
      .form-group
        .col-md-12
          %h5 Социальные сети                      
          = f.input :vkontakte, autofocus: true, :input_html => {:class => "form-control"}, :required => false, placeholder: "vk.com/username"
          = f.input :odnoklassniki, autofocus: true, :input_html => {:class => "form-control"}, :required => false, placeholder: "ok.ru/yourpage"
          = f.input :facebook, autofocus: true, :input_html => {:class => "form-control"}, :required => false, placeholder: "www.facebook.com/username"
          = f.input :twitter, autofocus: true, :input_html => {:class => "form-control"}, :required => false, placeholder: "twitter.com/username"
          = f.input :linkedin, autofocus: true, :input_html => {:class => "form-control"}, :required => false, placeholder: "www.linkedin.com/yourpage"
      %br
    = f.actions do
      .form-group
        .col-md-12 
          %br
          = f.submit "Изменить данные", :class => "input btn btn-primary"
          &nbsp
          &nbsp
          &nbsp
          = link_to "Отмена", :back, :class => "input btn backbtn"